_indian_labels_to_common = {
    "O": "O",
    "WITNESS": "I_WITNESS",
    "STATUTE": "C_LAW",
    "RESPONDENT": "I_RESPONDENT",
    "PROVISION": "I_PROVISION",
    "PRECEDENT": "I_PRECEDENT",
    "PETITIONER": "I_PETITIONER",
    "OTHER_PERSON": "I_OTHER_PERSON",
    "ORG": "C_ORG",
    "LAWYER": "C_LAWYER",
    "JUDGE": "C_JUDGE",
    "GPE": "C_LOCATION",
    "DATE": "I_DATE",
    "COURT": "C_COURT",
    "CASE_NUMBER": "I_CASE_NUMBER",
}

_german_labels_to_common = {
    "AN": "C_LAWYER",
    "EUN": "G_EUN",
    "GRT": "C_COURT",
    "GS": "C_LAW",
    "INN": "C_ORG",
    "LD": "C_LOCATION",
    "LDS": "C_LOCATION",
    "LIT": "G_LIT",
    "MRK": "C_ORG",
    "ORG": "C_ORG",
    "PER": "G_PER",
    "RR": "C_JUDGE",
    "RS": "G_RS",
    "ST": "C_LOCATION",
    "STR": "C_LOCATION",
    "UN": "C_ORG",
    "VO": "G_VO",
    "VS": "G_VS",
    "VT": "G_VT",
    "O": "O",
}

COMMON_LABELS = [
    "B-C_COURT",
    "B-C_JUDGE",
    "B-C_LAW",
    "B-C_LAWYER",
    "B-C_LOCATION",
    "B-C_ORG",
    "B-G_EUN",
    "B-G_LIT",
    "B-G_PER",
    "B-G_RS",
    "B-G_VO",
    "B-G_VS",
    "B-G_VT",
    "B-I_CASE_NUMBER",
    "B-I_DATE",
    "B-I_OTHER_PERSON",
    "B-I_PETITIONER",
    "B-I_PRECEDENT",
    "B-I_PROVISION",
    "B-I_RESPONDENT",
    "B-I_WITNESS",
    "I-C_COURT",
    "I-C_JUDGE",
    "I-C_LAW",
    "I-C_LAWYER",
    "I-C_LOCATION",
    "I-C_ORG",
    "I-G_EUN",
    "I-G_LIT",
    "I-G_PER",
    "I-G_RS",
    "I-G_VO",
    "I-G_VS",
    "I-G_VT",
    "I-I_CASE_NUMBER",
    "I-I_DATE",
    "I-I_OTHER_PERSON",
    "I-I_PETITIONER",
    "I-I_PRECEDENT",
    "I-I_PROVISION",
    "I-I_RESPONDENT",
    "I-I_WITNESS",
    "O",
]
COMMON_LABEL_TO_IDX = {l: i for i, l in enumerate(COMMON_LABELS)}
COMMON_IDX_TO_LABEL = {i: l for i, l in enumerate(COMMON_LABELS)}

INDIAN_TO_COMMON = {
    0: 42,
    1: 41,
    2: 23,
    3: 40,
    4: 39,
    5: 38,
    6: 37,
    7: 36,
    8: 26,
    9: 24,
    10: 22,
    11: 25,
    12: 35,
    13: 21,
    14: 34,
    15: 20,
    16: 2,
    17: 19,
    18: 18,
    19: 17,
    20: 16,
    21: 15,
    22: 5,
    23: 3,
    24: 1,
    25: 4,
    26: 14,
    27: 0,
    28: 13,
}

GERMAN_TO_COMMON = {
    0: 3,
    1: 6,
    2: 0,
    3: 2,
    4: 5,
    5: 4,
    6: 4,
    7: 7,
    8: 5,
    9: 5,
    10: 8,
    11: 1,
    12: 9,
    13: 4,
    14: 4,
    15: 5,
    16: 10,
    17: 11,
    18: 12,
    19: 24,
    20: 27,
    21: 21,
    22: 23,
    23: 26,
    24: 25,
    25: 25,
    26: 28,
    27: 26,
    28: 26,
    29: 29,
    30: 22,
    31: 30,
    32: 25,
    33: 25,
    34: 26,
    35: 31,
    36: 32,
    37: 33,
    38: 42,
}
